### ISSUE TITLE
Hunt down and fix faulty .mod files

### ISSUE THREAD

**Issue by DeerTears** [DeerTears/GB-Studio-Community-Assets#20] opened 2020-10-26 20:18 UTC
Some users have reported mod files (some composed by me) that prevent their games from building, even though I've tested nearly every song that's been added. If saving the contents as a new .mod file through OpenMPT doesn't fix these files then I don't know what the problem is or why it's happening to old .mod files.

#17 might be a good solution to help prevent this issue from occuring if for some reason storing .mod files on Github causes them to get changed in a way that makes GBT Player unhappy.

Ultimately, it'd be awesome to have help hunting down and noting the names of the .mod files that are problematic in this issue's comments so they can be tested and hopefully fixed.

**Comment by DeerTears** [comment] 2021-07-14 20:18
![is this why its broken](https://user-images.githubusercontent.com/47726614/125687118-3ea52653-17db-4cf1-8ced-9b0b40bc9367.PNG)

I saw this message when I was deleting a redundant .mod file and I wonder if this change of line endings is causing the data to be mis-read when converted to instructions for the rom. OpenMPT seems to read these just fine, so I wonder if there's a way to reconvert line-endings on download. That's assuming this is the issue, at least.

**Comment by mxashlynn** [comment] 2021-11-02 16:10
I enabled git lfs for this repo which should prevent the line ending issue from happening again in the future.

I'll use Excited_Suspense.mod as an example and see if I can figure out exactly what the issue is.

As a fallback, I'll resave everything using OpenMPT, though we might need new versions of some of the mods if they are already corrupted....

**Comment by mxashlynn** [comment] 2021-12-21 00:08
I tested every .mod in this repo with GB Studio 2.0 beta 5 and all of them now build without error.
I believe that re-encoding them for git-lfs must have corrected whatever the corruption problem was.
I can't vouch that everything is playing correctly, but I didn't notice anything that sounded obviously wrong.

I'm closing this issue.  If we get new reports we can dig deeper!

**Closed by mxashlynn** 2021-12-21 00:08 UTC
Labels: bug
